[package]
name = "nanom"
version = "0.1.4"
edition = "2021"
description = "Lightweight helper library for authoring native node modules"
license = "MIT"

[dependencies.napi-sys]
version = "2.4.0"
features = ["napi9", "dyn-symbols"]

[dependencies]
nanom-derive = "0.1.1"
